### ISSUE TITLE
PHP Warning:  "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by wild-dagger** [RJWoodhead/dokuwiki-plugin-phprestrict#5]
`php-fpm --version`

> PHP 7.3.9 (fpm-fcgi) (built: Aug 29 2019 12:55:30)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies

`cat /var/log/lighttpd/error.log | grep phprestrict | tail -1`
> 2019-09-04 13:38:18: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /srv/http/lib/plugins/phprestrict/action/action.php on line 68

`cat  /srv/http/lib/plugins/phprestrict/action/action.php | grep continue`
> continue;	// try next path

**Comment by RJWoodhead** [comment]
Yes, I believe you are entirely correct, and I have been tripped up by PHP semantics. I have pushed your suggested correction. TYVM for noticing this.
